2025-01-04 16:59:24,429 - ERROR - Exception on /profile/edit [GET]
Traceback (most recent call last):
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\routes.py", line 197, in edit_profile
    return render_template('edit_profile.html', form=form)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\templates\edit_profile.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\templates\base.html", line 240, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\templates\edit_profile.html", line 14, in block 'content'
    {% if student.photo %}
    ^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'student' is undefined
2025-01-04 16:59:29,926 - ERROR - Exception on /profile/edit [GET]
Traceback (most recent call last):
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\routes.py", line 197, in edit_profile
    return render_template('edit_profile.html', form=form)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\templates\edit_profile.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\templates\base.html", line 240, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\templates\edit_profile.html", line 14, in block 'content'
    {% if student.photo %}
    ^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'student' is undefined
2025-01-04 16:59:37,696 - INFO - Logging is set up.
2025-01-04 16:59:43,813 - ERROR - Exception on /profile/edit [GET]
Traceback (most recent call last):
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\routes.py", line 197, in edit_profile
    return render_template('edit_profile.html', form=form)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\templates\edit_profile.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\templates\base.html", line 240, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\Documents\GitHub\olympiad_time\app\templates\edit_profile.html", line 14, in block 'content'
    {% if student.photo %}
    ^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'student' is undefined
2025-01-04 17:05:32,929 - INFO - Logging is set up.
